[db]
db_user = "admin"
db_password = "123"
db_database = "go_api"
db_host = "127.0.0.1"
db_port = 3306

[logger]
log_level = "INFO"
log_file = "./logs/log.log"
log_trace_on = false
log_prod_on = false

[server]
server_host="localhost"
server_port="4501"

[rabbit]
rabbit_user = "guest"
rabbit_password = "guest"
rabbit_host = "127.0.0.1"
rabbit_port = 50051
